name: example_2

on:
  push:
    branches:
      - main


jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Run a one-line script"
        run: echo "Hello, world!"
      - name: Set a env value
        id: checkout_code
        run: echo "some_output=Hello, world!" >> $GITHUB_OUTPUT
      - name: "uses previous step output"
        run: echo "The previous step output was ${{ steps.checkout_code.outputs.some_output }}"
    outputs:
      salida: ${{ steps.checkout_code.outputs.some_output }}

  second_job:
    needs: first_job
    env:
      EXAMPLE_VAR: "example_value"
      salida: ${{ needs.first_job.outputs.salida }}
    runs-on: ubuntu-latest
    steps:
      - name: "Echo the environment variable"
        run: echo "The value of EXAMPLE_VAR is $EXAMPLE_VAR"
      - name: "Show current contents"
        run: ls -la
      - name: "Show current directory"
        run: pwd
      - name: "Run a multi-line script"
        uses: actions/checkout@v2
      - name: "Echo the output from the first job"
        run: echo "The output from the first job is $salida"s
  third_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Create a file"
        run: echo "This is a file created in the third job." > example_file.txt
      - name: "Display the file"
        run: cat example_file.txt
      - name: "Upload the file as an artifact"
        uses: actions/upload-artifact@v4
        with:
          name: example_file
          path: example_file.txt
  fourth_job:
    needs: [third_job]
    runs-on: ubuntu-latest
    steps:
      - name: "Download the artifact from third job"
        uses: actions/download-artifact@v4
        with:
          name: example_file
      - name: "Display the downloaded file"
        run: cat example_file.txt
      - name: "Run a script that uses the artifact"
        run: echo "Using the downloaded artifact in a script."

