name: example_2

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Run a one-line script"
        run: echo "Hello, world!"
      - name: "Run a script that fails"
        run: cat not_existing.txt

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: "Run another one-line script"
        run: echo "Hello, world!"

