name: example_2

on:
  push:
    branches:
      - main


jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Run a one-line script"
        run: echo "Hello, world!"

  second_job:
    needs: first_job
    env:
      EXAMPLE_VAR: "example_value"
    runs-on: ubuntu-latest
    steps:
      - name: "Echo the environment variable"
        run: echo "The value of EXAMPLE_VAR is $EXAMPLE_VAR"
      - name: "Show current contents"
        run: ls -la
      - name: "Show current directory"
        run: pwd
      - name: "Run a multi-line script"
        uses: actions/checkout@v2
      - name: Set a env value
        id: checkout_code
        run: echo "some_output=Hello, world!" >> $GITHUB_OUTPUT
      - name: "uses previous step output"
        run: echo "The previous step output was ${{ steps.checkout_code.outputs.some_output }}"

