name: example_2

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Run a one-line script"
        run: echo "Hello, world!"

  second_job:
    needs: first_job
    env:
      EXAMPLE_VAR: "example_value"
    runs-on: ubuntu-latest
    steps:
      - name: "Run another one-line script"
        run: echo "Hello, world!"

